### ISSUE TITLE
add kerberos support

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/pepper#34]
Add kerberos authentification support.

It is likely we will contribute a patch for this in the near future.

**Comment by arthurlogilab** [comment]
would it be ok to add a dependency on requests-keberos https://pypi.python.org/pypi/requests-kerberos ?

**Comment by whiteinge** [comment]
Kerberos support in Pepper would be fine as long as it is an _optional_ requirement. In other words, no additional deps or steps must be required for Pepper to function as it does now. If Kerberos support is needed then additional software and configuration can be done.

Cross-linking saltstack/salt#24793 since the conversation there will also shape what Kerberos support in Pepper ends up looking like.

**Comment by arthurlogilab** [comment]
OK. we'll find a way to have a configuration switch that enables this optional import.
