### ISSUE TITLE
CameCase in Python code

### ISSUE THREAD

**Issue by kottenator** [saltstack/pepper#43]
According to PEP8 you should use camel case for `ClassName` only and underscores for everything else, but you use it for variables in your code (`nodesJidRet`, etc). I know it's not a bug. But it'd be nice to follow PEP8

**Comment by whiteinge** [comment]
This project follows the same [style recommendations as the main Salt project](http://docs.saltstack.com/en/latest/topics/development/conventions/style.html). The code you mentioned should indeed be fixed. (Actually it should be removed entirely per our discussion in #40 since Pepper should not be running Salt commands for no reason.)

**Comment by kottenator** [comment]
Thanks for the quick answer. I can't wait for Pepper stable release (because it's the only and the official Salt remote CLI). Thank you for making such a great tool!

**Comment by whiteinge** [comment]
Closing since the mentioned style nit was since fixed. Any remaining style issues can be addressed in new issues or PRs.
